# -*- coding: utf-8 -*-
"""Copy of One sample T-Test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hAzsq5Ex_liemt8vkSUm9sn0OCJcrzps
"""

import pandas as pd
import numpy as np
!pip install afinn
from afinn import Afinn
afinn = Afinn(language='en')
!pip install researchpy
import researchpy as rp
import scipy.stats as stats
import matplotlib.pyplot as plt
from google.colab import files
from google.colab import drive

# loading the data set
df = pd.read_csv("/content/Datafiniti_Amazon_Consumer_Reviews_of_Amazon_Products.csv")
df.info()

# applying sentiment score from afinn library
df['reviews.text']= df['reviews.text'].astype(str)
df['sentiment'] = df['reviews.text'].apply(afinn.score)
#df['hashtagssentiment'] = df['hashtags'].apply(afinn.score)
#df["date"] = df["date"].astype('datetime64[ns]') 
#df["date"] = df.date.dt.to_pydatetime()
df.head()



#stats spread
df['sentiment'].describe()

#only sentiment score column and name of product, saving into data set for mapreduce to aggregate
ImptColumns = ['name', 'sentiment']
df.loc[:,ImptColumns].to_csv('data.csv')
files.download("data.csv")

#sorting the most negative sentiments from head
ImptColumns = ['reviews.text', 'sentiment']

df.sort_values(by='sentiment')[ImptColumns].head(10)

#sorting most positive sentiments from tail
df.sort_values(by='sentiment')[ImptColumns].tail(10)

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

df['sentiment'].hist()

#save the image
plt.savefig('/content/img.png')

#group by each product
df.groupby('name')['sentiment'].describe()







